[General]
LoggingOn=true
NormalMessageToConsole=true
TraceInfoLevel=info
ChartContainerHeight=650
ChartBackgroundImage=
IgnoreDataErrors=true
GeneratejQueryInclude=false
DoLibraryIncludes=false
Language=nl-NL
;Language=en-GB
UseSQL=false
UseScrollableTables=true
RecordsBeganDate=01/01/20
MaxErrors=10
CMXport=8998
UseSpecificHighchartsVersion=
DoModular=false
ModulePath=
NeedSolarEnergyDailyValuesInCSV=false
CheckDateOrder=true
ConnectNulls=false
ParamCleanUp=false
LastUploadTime=04/07/26 09:50

[pwsFWI]
Analyse=90
WarningLevel=5
ResultFormat=beteljuice
FireImage=true
PredictionBackground=Moccasin
CurrentIndexFormat=Standard
;CurrentIndexFormat=Betel-Kocher
CurrentPwsFWI=<span id='CurrentPwsFWI' style="border: 1px solid black;cursor:pointer;text-align:center;background:green;color: white"> &nbsp;75.0&nbsp;pwsFWI</span>
CurrentIndexDay=today

[Top10]
BackgroundColorHeader=#d0d0d0
BackgroundColorTable=#f0f0f0
TextColorAccentTable=DarkOrange
TextColorHeader=Green
NumberOfColumns=4

[NOAA]
FTPDirectory=./Reports/
ColorNOAAText=Black
ColorNOAABackground=#f9f8EB
StartInCurrentMonth=true

[Graphs]
UseHighchartsBoostModule=true
UseNormalTempReference=both
UseNormalRainReference=both
MaxNrOfSeriesVisibileInGraph=3
PeriodMovingAverage=180
WindRoseNrOfWindforceClasses=6
WindRoseMaxWindSpeed=60
WindRoseInversed=false
WindrunClassWidth=75
DailyRain=true
MonthlyRain=true
YearRainstats=true
YearMonthRainstats=true
MonthlyTemp=true
YearTempstats=true
YearMonthTempstats=true
WarmerDays=true
HeatMap=true
WindRose=true
Windrun=true
SolarHours=true
SolarEnergy=true
SolarHoursYearMonth=true
SolarEnergyYearMonth=true
TempSum=true
GrowingDegreeDays=true
Seasons=true
DailyEVT=true
MonthlyEVT=true
AverageClash=true
GraphColors=
;GraphColors=['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4']
WindRoseColors=
;WindRoseColors=['lightgrey', 'green', 'blue', 'yellow', 'orange', 'red', 'deeppink', 'purple', 'black']
HeatmapNumberOfYearsPerPage=10
GrowingDegreeDaysReferenceTemp=5
WinterToSpringTemperatureLimit=4
SpringToSummerTemperatureLimit=14
EVTvsRAIN=true
RAINvsEVT=true
FrostDays=true

[FTP site]
DoUploadFTP=true
UploadDir=
FtpLog=off
MaxConcurrentUploads=
delayMilliSeconds=100

[Maps]
Website=https://meteo-wagenborgen.nl/
Participant=true
DoneToday=2026-07-04T07:51:04

[Website]
StatisticsType=Google
GoogleStatsId=G-39Q8YBXL08
MatomoTrackerUrl=
MatomoSiteId=
PermitGoogleOptout=true
CumulusRealTimeLocation=
ShowInsideMeasurements=true
CumulusRealTimeInterval=30
PwsfwiButtonInHeader=false
ShowUV=true
ShowSolar=true
;HeaderLeftText=Home of <a href='https://cumulus.hosiene.co.uk/viewtopic.php?f=44&t=17998' style='color:black' target='_blank'>CumulusUtils</a><br/>Currently Experimenting/Development<br/>Things may not function
HeaderLeftText=Home of <a href='https://cumulus.hosiene.co.uk/viewtopic.php?f=44&t=17998' style='color:lightgrey' target='_blank'>CumulusUtils</a>
;<br/>Donations welcome via <a href='https://www.paypal.com/paypalme/MeteoWagenborgen' style='color:lightgrey' target='_blank'>PayPal</a>
;HeaderRightText=<img src="https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_Groningen.svg" alt="Coat of Arms" style="padding: 10px; width:120px; height:auto;" />
HeaderRightText=<a href="https://cumulussites.net/index.php?a=in&u=HansR"><img src="https://cumulussites.net/button.php?u=HansR" alt="Cumulus Top Sites"/></a>
SiteTitleAddition=
UseCMXMoonImage=false
MoonImageLocation=https://meteo-wagenborgen.nl/images/moon.png
ColorMenuBackground=Lightgrey
ColorMenuText=Black
ColorDropdownMenuBackground=Lightgrey
ColorDropdownMenuText=Black
ColorDropdownMenuHoverBackground=Silver
ColorDropdownMenuHoverText=Black
ColorTitleBar=#E87510
ColorTitleText=White
ColorDashboardCellTitleBarBackground=#C5C55B
ColorDashboardCellTitleBarText=White
ColorDashboardCellText=Black
ColorDashboardCellBackground=White
ColorReportviewText=black
ColorReportviewBackground=white
ColorReportviewTableData=Black
ColorFooterLink=#E87510
ColorFooterLinkHover=OrangeRed
ColorFooterBackground=lightgrey
ColorFooterText=Black
ColorBodyBackground=White
;ColorDashboardTextAccent=Chartreuse
ColorDashboardTextAccent=Red
ColorToggler=Black
ColorDashboardUpIndicator=Chartreuse
ColorDashboardDownIndicator=Red
SteelseriesFramedesign=SHINY_METAL
;SteelseriesFramedesign=BLACK_METAL
SteelseriesBackgroundColor=BROWN
SteelseriesPointerColour=RED
SteelseriesPointerType=type3
SteelseriesDirAvgPointertype=TYPE3
SteelseriesDirAvgPointerColour=BLUE
SteelseriesLcdColour=ORANGE
SteelseriesForegroundType=type1
SteelseriesKnobType=STANDARD_KNOB
SteelseriesKnobStyle=SILVER
SteelseriesRainUseSectionColours=true
SteelseriesRainUseGradientColours=true
SteelseriesTempThresholdValue=30
SteelseriesLedVisible=false
ThresholdTempVisible=true
ThresholdTempValue=30
ThresholdHumidityVisible=true
ThresholdHumidityValue=80
ThresholdWindVisible=true
ThresholdWindValue=30
ThresholdRainVisible=true
ThresholdRainValue=20
ThresholdRRateVisible=true
ThresholdRRateValue=10
ThresholdUVVisible=true
ThresholdUVValue=8
Panel-1=TemperatureText
Panel-2=PressureText
Panel-3=RainText
Panel-4=Clocks
Panel-5=WindGauge1
Panel-6=WindDirGauge1
Panel-7=WindRoseGauge1
Panel-8=WindText
Panel-9=SolarDisc
Panel-10=LunarDisc
Panel-11=HumidityText
Panel-12=SolarText
Panel-13=TemperatureGauge
Panel-14=OtherTempsGauge
Panel-15=PressureGauge
Panel-16=HumidityGauge
Panel-17=WindGauge2
Panel-18=WindDirGauge2
Panel-19=WindRoseGauge2
Panel-20=CloudBaseGauge
Panel-21=RainGauge
Panel-22=RainSpeedGauge
Panel-23=SolarGauge
Panel-24=UVGauge
ColorTitleBackGroundImage=HPIM3899_day.JPG
ColorTitleBackGroundImageCivil=HPIM3899_civil.JPG
ColorTitleBackGroundImageNautical=HPIM3899_nautical.JPG
ColorTitleBackGroundImageAstronomical=HPIM3899_astronomical.JPG
ColorTitleBackGroundImageNight=HPIM3899_night.JPG
FooterCenterText=

[SysInfo]
ReportWidth=800
SystemInfoLinesToSkip=
Tx=1
ExtraStationInfo=WS80/WS40
SystemInfoMenu=true

[Thrifty]
Top10RecordsPeriod=1
RainGraphsPeriod=1
TempGraphsPeriod=1
WindGraphsPeriod=1
MiscGraphsPeriod=1
MapsPeriod=1
SolarGraphsPeriod=1

[StationMap]
StationMapMenu=true
Zoomlevel=13
CompassRosePosition=bottomright
CompassRoseType=2
WindArrowType=1
ArrowLatitude=53.2589
ArrowLongitude=6.9306

[Compiler]
SmaPeriod=180
DoneToday=2026-07-04T07:51:04

[MeteoCam]
MeteoCamMenu=true
MeteoCamDir=./MeteoCam
TimelapseExtension=mp4
MeteoCamName=meteocam.jpg
CamType=EcowittHP10
FontSize=24
FontWeight=bold
BottomOffset=60
BlockLeftOrRight=right
BorderOffset=25
TextAlign=right
TextColor=lightblue
WantToSeeLines=WTPHR

[AirLink]
CountrySelected=EU
WantToSeeNow=true
WantToSeeNowCast=false
WantToSee1hr=true
WantToSee3hr=true
WantToSee24hr=true
WantToSeeWind=false
CleanupAirlinkLogs=false
StandAloneModule=false
ReferenceLineThickness=2

[ExtraSensors]
ExtraSensors=true
ParticipatesSensorCommunity=true
CleanupExtraSensorslog=false
UserModificationExtraSensorCharts=true
ExternalExtraSensors=
ExtraTemp=1,2,3,4
ExtraHum=1,2,3,4
ExtraDP=1,2,3,4
SoilTemp=
SoilMoisture=1,2
AirQuality=
UserTemp=1
LeafWetness=
SoilTemperature=
CO2=1
LightningSensor=true
LaserDist=
LaserDepth=

[CustomLogs]
CustomLogs=true
UserModificationCustomLogsCharts=false
ExcludedCustomLogs=
DoneToday=2026-07-04T09:51:05

[Diary]
ColorDiaryText=Black
ColorDiaryBackground=#f9f8EB
ColorDiaryChartSnowDepth=#EBBD33
ColorDiaryChartSnow24h=blue
Diary=true

[Forecasts]
ForecastSystem=CUtils
